import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { PartiesProvider } from "@/context/PartiesContext";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Political Compass",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <PartiesProvider>{children}</PartiesProvider>
      </body>
    </html>
  );
}
